### ISSUE TITLE
options too long

### ISSUE THREAD

**Issue by YangSeungWon** [YangSeungWon/42bot#4]
app_1    | [ERROR]  web-api:WebClient:0 failed to match all allowed schemas [json-pointer:/blocks/4/accessory/options/0/text]
app_1    | [ERROR]  web-api:WebClient:0 must be less than 151 characters [json-pointer:/blocks/4/accessory/options/0/text/text]
app_1    | Error: An API error occurred: invalid_blocks
app_1    |     at platformErrorFromResult (/usr/src/app/node_modules/@slack/web-api/dist/errors.js:56:33)
app_1    |     at WebClient.apiCall (/usr/src/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
app_1    |     at runMicrotasks (<anonymous>)
app_1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1    |     at async /usr/src/app/index.js:147:9
app_1    |     at async Array.<anonymous> (/usr/src/app/node_modules/@slack/bolt/dist/middleware/builtin.js:170:9)
app_1    |     at async Array.onlyActions (/usr/src/app/node_modules/@slack/bolt/dist/middleware/builtin.js:17:5) {
app_1    |   code: 'slack_webapi_platform_error',
app_1    |   data: {
app_1    |     ok: false,
app_1    |     error: 'invalid_blocks',
app_1    |     response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
app_1    |   }
app_1    | }

**Comment by YangSeungWon** [comment]
adding all voters name to the options seems not sustainable.
think about removing names from the poll option(simplify them with selected emojis) and create another button to see who voted on what.

**Comment by YangSeungWon** [comment]
app_1    | [ERROR]  web-api:WebClient:0 must be less than 76 characters [json-pointer:/blocks/1/elements/1/text/text]
app_1    | [ERROR]  web-api:WebClient:0 failed to match all allowed schemas [json-pointer:/blocks/1/elements/2/text]
app_1    | [ERROR]  web-api:WebClient:0 must be less than 76 characters [json-pointer:/blocks/1/elements/2/text/text]
app_1    | Error: An API error occurred: invalid_blocks
app_1    |     at platformErrorFromResult (/usr/src/app/node_modules/@slack/web-api/dist/errors.js:56:33)
app_1    |     at WebClient.apiCall (/usr/src/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
app_1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1    |     at async /usr/src/app/index.js:42:9
app_1    |     at async Array.<anonymous> (/usr/src/app/node_modules/@slack/bolt/dist/middleware/builtin.js:170:9)
app_1    |     at async Array.onlyActions (/usr/src/app/node_modules/@slack/bolt/dist/middleware/builtin.js:17:5) {
app_1    |   code: 'slack_webapi_platform_error',
app_1    |   data: {
app_1    |     ok: false,
app_1    |     error: 'invalid_blocks',
app_1    |     response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
app_1    |   }
app_1    | }

**Comment by YangSeungWon** [comment]
https://github.com/YangSeungWon/42bot/commit/f2c5f5f9005c3819e4a13d7ca88b93f4075d15d6
